module Client.ChildMenu

open Fable.Helpers.React
open Fable.Helpers.React.Props
open Fulma
open ClientModelMsg

let childMenu  (model : Model) (dispatch : UIMsg -> unit)=
    let navItem name menuMediator = Navbar.Item.a [ Navbar.Item.IsActive (model.MenuMediator = menuMediator)
                                                    Navbar.Item.Props [ OnClick (fun _ ->  menuMediator |> MenuSelected |> dispatch)] ]
                                        [ str name ]

    nav [ Class "child-menu" ]
        [ div [ Class "child-menu-inner" ]
            [ ul [ ]
                [ li [ Class "child-header" ]
                    [ div [ Class "sidebar-title" ]
                        [ str "Navigation" ]
                      a [ Id "close-child-menu"
                          Href "#"
                          Class "menu-wrapper" ]
                        [ span [ Class "icon-box-toggle ef-4" ]
                            [ span [ Class "rotate" ]
                                [ i [ Class "icon-line-top" ]
                                    [ ]
                                  i [ Class "icon-line-center" ]
                                    [ ]
                                  i [ Class "icon-line-bottom" ]
                                    [ ] ] ] ] ] ]
              ul [ Id "dashboard-menu"
                   Class "sidebar-menu is-active animated preFadeInRIght fadeInRight" ]
                [ li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "dashboard" ]
                              str "Dashboard" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "dashboard.html" ]
                                [ str "Main layout" ] ]
                          li [ ]
                            [ a [ Href "dashboard-blank.html" ]
                                [ str "Blank page" ] ]
                          li [ ]
                            [ a [ Href "dashboard-login.html" ]
                                [ str "Login page" ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "insert_chart" ]
                              str "Analytics" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "dashboard-chartjs.html" ]
                                [ str "Chart js" ] ]
                          li [ ]
                            [ a [ Href "dashboard-billboardjs.html" ]
                                [ str "Billboard js" ] ]
                          li [ ]
                            [ a [ Href "dashboard-peityjs.html" ]
                                [ str "Peity js" ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "developer_board" ]
                              str "Widgets" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "dashboard-widgets-data.html" ]
                                [ str "Data widgets" ] ]
                          li [ ]
                            [ a [ Href "dashboard-widgets-social.html" ]
                                [ str "Social widgets" ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "view_agenda" ]
                              str "Feed" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "dashboard-feed.html" ]
                                [ str "Social feed" ] ]
                          li [ ]
                            [ a [ Href "dashboard-feed-post.html" ]
                                [ str "Post Item" ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "invert_colors" ]
                              str "Styles" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "dashboard.html" ]
                                [ str "Light sidebar" ] ]
                          li [ ]
                            [ a [ Href "dashboard-dark-nav.html" ]
                                [ str "Dark sidebar" ] ] ] ] ]
              ul [ Id "documents-menu"
                   Class "sidebar-menu animated preFadeInRIght fadeInRight" ]
                [ li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "insert_drive_file" ]
                              str "Documents" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Document list"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Document details"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Invoice"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "assignment" ]
                              str "Projects" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Project list"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Project details"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "assignment_turned_in" ]
                              str "Tasks" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Task list"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Kanban board" ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "library_books" ]
                              str "Forms" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Step form"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Steps"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ] ]
              ul [ Id "business-menu"
                   Class "sidebar-menu animated preFadeInRIght fadeInRight" ]
                [ li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "group" ]
                              str "Contacts" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Contact list"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Contact grid"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Contact details"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "person_add" ]
                              str "Leads" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Leads list"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Add lead"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "attach_money" ]
                              str "Deals" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Deals list"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Single Deal"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ] ]
              ul [ Id "misc-menu"
                   Class "sidebar-menu animated preFadeInRIght fadeInRight" ]
                [ li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "grid_on" ]
                              str "Datatables" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Example 1"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Example 2"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Example 3"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "speaker_notes" ]
                              str "Faq" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Faq home"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Faq article"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "thumbs_up_down" ]
                              str "Forum" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Forum home"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Forum thread"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "email" ]
                              str "Mailbox" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Inbox"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Compose"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ] ]
              ul [ Id "settings-menu"
                   Class "sidebar-menu animated preFadeInRIght fadeInRight" ]
                [ li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "settings" ]
                              str "Global settings" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Preferences"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Change password"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "account_circle" ]
                              str "User settings" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "User list"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Add user"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Access rights"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ]
                  li [ Class "have-children" ]
                    [ a [ Class "parent-link"
                          Href "#" ]
                            [ span [ Class "material-icons" ]
                                [ str "domain" ]
                              str "Organizations" ]
                      ul [ ]
                        [ li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Organizations list"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ]
                          li [ ]
                            [ a [ Href "javascript:void(0);" ]
                                [ str "Add organization"
                                  span [ Class "sl sl-icon-lock warning-text ml-10" ]
                                    [ ] ] ] ] ] ] ] ]