module Client.NavMenu

open Fable.Helpers.React
open Fable.Helpers.React.Props
let menu =
    Menu.menu [ ]
        [ Menu.label [ ]
              [ str "General" ]
          Menu.list [ ]
              [ Menu.item [ ]
                    [ str "Dashboard" ]
                Menu.item [ ]
                    [ str "Customers" ] ]
          Menu.label [ ]
              [ str "Administration" ]
          Menu.list [ ]
              [ Menu.item [ ]
                  [ str "Team Settings" ]
                li [ ]
                    [ a [ ]
                        [ str "Manage Your Team" ]
                      Menu.list [ ]
                          [ Menu.item [ ]
                                [ str "Members" ]
                            Menu.item [ ]
                                [ str "Plugins" ]
                            Menu.item [ ]
                                [ str "Add a member" ] ] ]
                Menu.item [ ]
                    [ str "Invitations" ]
                Menu.item [ ]
                    [ str "Cloud Storage Environment Settings" ]
                Menu.item [ ]
                    [ str "Authentication" ] ]
          Menu.label [ ]
              [ str "Transactions" ]
          Menu.list [ ]
              [ Menu.item [ ]
                    [ str "Payments" ]
                Menu.item [ ]
                    [ str "Transfers" ]
                Menu.item [ ]
                    [ str "Balance" ] ] ]

